# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b4d638f65bf5a06f34735d72fc69d6bffadff3aa68844c9ecf00e65f5f9c4beb7dc52ba9e190aea5fdf44406e975c55bc0af59e802244fa84e1cb372337e0b

test:
  secret_key_base: ad0040fc57344d827b67e985ffd57c7e6b4d93ef679d65bbd99f360145d699133908cb90b585e8679c0bf4b00afc45c1e93cd89a82f2fd53dca8c11bf49359f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
